[package]
name = "flyer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = {version="0.9.3"}
noise = "0.8.0"
rand = "0.8.5"
rand_seeder = "0.2.3"
rand_chacha = "0.3.1"
aerso = { git = "https://github.com/rob-clarke/aerso.git" }
serde = "1.0"
serde_yaml = "0.9"
nalgebra = "0.32.3"
kiddo = "2.1.1"
